// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnuXk_F15VWZHjISkRD0RfWTjAM6l1uOw',
    appId: '1:554696928368:web:06097f0658dc3b57fcd8b5',
    messagingSenderId: '554696928368',
    projectId: 'digital-recipe-app',
    authDomain: 'digital-recipe-app.firebaseapp.com',
    storageBucket: 'digital-recipe-app.appspot.com',
    measurementId: 'G-G2BQSLX9JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6-qAM0b1tloGfyMTR2lwBBOFb1HRPpgs',
    appId: '1:554696928368:android:2ab9d8b62e8df3d7fcd8b5',
    messagingSenderId: '554696928368',
    projectId: 'digital-recipe-app',
    storageBucket: 'digital-recipe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGEVi6n4CWRVMLCWbR0et7wr0FtbHLkJo',
    appId: '1:554696928368:ios:0c3628c95c5d25a4fcd8b5',
    messagingSenderId: '554696928368',
    projectId: 'digital-recipe-app',
    storageBucket: 'digital-recipe-app.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGEVi6n4CWRVMLCWbR0et7wr0FtbHLkJo',
    appId: '1:554696928368:ios:0c3628c95c5d25a4fcd8b5',
    messagingSenderId: '554696928368',
    projectId: 'digital-recipe-app',
    storageBucket: 'digital-recipe-app.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
